### PR TITLE
Code refactor with try catch

### LINKED ISSUE #15: Un-catch exception
```
Caused by android.os.DeadObjectException
android.os.BinderProxy.transactNative (BinderProxy.java)
com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer (InstallReferrerClientImpl.java:8)
com.analytics.blotout.referral.InstallRefferal.getReferrerData (InstallRefferal.kt:47)
com.analytics.blotout.referral.InstallRefferal.access$getReferrerData (InstallRefferal.kt:8)
com.analytics.blotout.referral.InstallRefferal$startClient$1.onInstallReferrerSetupFinished (InstallRefferal.kt:21)
com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected (InstallReferrerClientImpl.java:5)
```

reported by customer

### PR DESCRIPTION
**Pull request by nitinblotout**
Resolves #15

### CODE REVIEW

File: blotoutSDK/src/main/java/com/analytics/blotout/geasture/Gesture.java [hunk 1]
```diff
@@ -271,7 +260,7 @@ public void setLongPressTimeout(long longPressTimeout) {
 
   private void checkNotNull(Object object, String message) {
     if (object == null) {
-      throw new IllegalArgumentException(message);
+      //throw new IllegalArgumentException(message);
```
Comment (NejcZdovc) [inline blotoutSDK/src/main/java/com/analytics/blotout/geasture/Gesture.java:263]: what should we do here? log?

Comment (nitinblotout) [reply blotoutSDK/src/main/java/com/analytics/blotout/geasture/Gesture.java]: made changes to implemented  it in another way. 

-> There is no chances to receive listener object as null.

**Review by NejcZdovc — APPROVED** [review]
